- name: Install OneDrive sync
  aur:
    name: onedrive-abraunegg
    skip_installed: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- include: wine.yml
  when: ansible_facts['os_family'] == 'Archlinux'
