- hosts: localhost

  vars:
    packages: ['curl', 'direnv', 'git', 'gpg', 'wget', 'neovim', 'tmux', 'zsh', 'bzip2', 'sqlite3']
    packages_debian: ['silversearcher-ag', 'keychain']
    packages_macos:  ['the_silver_searcher']
    x11_packages: ['xcape', 'arandr', 'autorandr', 'maim', 'xclip']
    x11_packages_debian: ['xorg', 'i3']
    calendar_packages: ['todoman', 'vdirsyncer', 'pass', 'khal']
    asdf_version: 'v0.8.1'
    asdf_keyrings_dir: ~/.asdf/keyrings/

  tasks:
    - name: Install Git and configure ansible
      include_tasks: tasks/bootstrap.yml
      tags: bootstrap

    - name: Install packages defined in vars
      include_tasks: tasks/packages.yml
      tags: packages

    - name: Install and configure zsh and oh-my-zsh
      include_tasks: tasks/zsh.yml
      tags: zsh

    - name: Install and configure asdf
      include_tasks: tasks/asdf.yml
      tags: asdf

    - name: Set up dotfiles and dotfiles-local
      include_tasks: tasks/dotfiles.yml
      tags: dotfiles

    - name: Set up UFW on Linux
      include_tasks: tasks/firewall.yml
      when: ansible_facts['os_family'] != 'Darwin'
      tags: firewall

    - name: Set up NTP on Linux
      include_tasks: tasks/ntp.yml
      tags: ntp
      when: ansible_facts['os_family'] != 'Darwin'

    - name: Install and configure X11 on Linux
      include_tasks: tasks/x11.yml
      when: ansible_facts['os_family'] != 'Darwin'
      tags: x11

    - name: Install and configure dev environment
      include_tasks: tasks/development.yml
      tags: [ development, docker, postgresql ]

    - include_tasks: tasks/powersafe.yml
      tags: powersafe
      when: ansible_hostname == 'hotmilk'

    - name: Install encryption packages
      package:
        name: ['gnupg', 'pass']
      become: yes
      when: ansible_facts['os_family'] != 'Darwin'

    - name: Install encryption packages
      homebrew:
        name: ['gnupg', 'pass']
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Install fonts
      include_tasks: tasks/fonts.yml
      tags: fonts

    - name: Install Syncthing
      include_tasks: tasks/syncthing.yml
      tags: syncthing

    # - include_tasks: tasks/rslsync.yml
    #   tags: rslsync
    #   when: ansible_facts['os_family'] != 'Darwin'

    - include_tasks: tasks/backup.yml
      tags: backup
      when: ansible_facts['os_family'] != 'Darwin'

    - include_tasks: tasks/onedrive.yml
      tags: onedrive
      when: ansible_facts['os_family'] != 'Darwin'

    - include_tasks: tasks/code.yml
      tags: code

    - include_tasks: tasks/calendar.yml
      tags: calendar

    - include_tasks: tasks/homebrew.yml
      tags: homebrew

    - name: Install all those lovely applications
      package:
        name: ['mplayer', 'vlc', 'anki']
        state: present
      become: yes
      when: ansible_facts['os_family'] != 'Darwin'
      tags: [ desktop, applications ]

    - name: Install Emacs
      include_tasks: tasks/emacs.yml
      tags: emacs

  handlers:
    - name: run rcup
      command: env RCRC=$HOME/dotfiles/rcrc rcup
    - name: run doom sync
      command: doom sync
    - name: reread systemd configs
      systemd:
        daemon_reload: yes
      become: yes
    - name: source asdf.sh
      command: source ~/.asdf/asdf.sh
