- hosts: localhost
  roles:
    - bootstrap
    - common
    - dotfiles
    - firewall
    - backup
    - caldav
    - email
    - powersafe
    - development
    - { role: X11, when: ansible_os_family != 'Darwin' }
