- hosts: localhost
  roles:
    - bootstrap
    - common
    - dotfiles
    - bluetooth
    - firewall
    - backup
    - calendar
    - email
    - powersafe
    - development
    - { role: X11, when: ansible_os_family != 'Darwin' }
    - ioki
  tasks:
    - include_tasks: rslsync.yml
      tags: rslsync
