- hosts: localhost
  roles:
    - bootstrap
    - common
    - dotfiles
    - firewall
    - caldav
    - i3
    # Mediakeys role was initially created for Wayland. When using i3,
    # all of the media keys are configured in the i3 config.
    # - { role: mediakeys, when: ansible_os_family == 'Archlinux' }
