---

- package:
    name: ['borgbackup', 'pass']
    state: present
  become: yes
  when: ansible_facts['os_family'] != 'Darwin'
  tags: backup

# - name: Enable borgbackup timer
#   systemd:
#     name: borgbackup.timer
#     scope: user
#     enabled: yes
#   when: ansible_facts['os_family'] == 'Archlinux'
#   tags: backup
