---
- package:
    name: '{{ calendar_packages }}'
    state: present
  become: yes
  when: ansible_facts['os_family'] != 'Darwin'
  tags: calendar

- homebrew:
    name: '{{ packages }}'
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags: calendar

- name: Enable vdirsyncer timer
  systemd:
    name: vdirsyncer.timer
    scope: user
    enabled: yes
  when: ansible_facts['os_family'] != 'Darwin'
  tags: calendar

