---
# direnv is used for development at ioki
- name: Ensure direnv is installed on Linux
  package:
    name: direnv
    state: present
  become: yes
  when: ansible_facts['os_family'] != 'Darwin'
  tags: development

- name: Ensure direnv is installed on macOS
  homebrew:
    name: direnv
  when: ansible_facts['os_family'] == 'Darwin'
  tags: development

- name: Ensure libpq is installed on Ubuntu - dependency for pg gem
  apt:
    name: libpq-dev
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Debian'
  tags: ['development', 'postgresql']

# https://stackoverflow.com/a/50349235
- name: Set low precedence for api.rubygems.org IPv6 addresses on Linux
  lineinfile:
    path: /etc/gai.conf
    regexp: '^precedence  2a04:4e42::0/32'
    line: 'precedence  2a04:4e42::0/32  5'
    create: yes
  become: yes
  when: ansible_facts['os_family'] != 'Darwin'
  tags: development
