---
- name: Ensure RCM is installed on Linux
  apt:
    name: rcm
  become: yes
  when: ansible_os_family != 'Darwin'
  tags: dotfiles

- name: Ensure RCM is installed on macOS
  homebrew_tap:
    name: thoughtbot/formulae
  when: ansible_os_family == 'Darwin'
  tags: dotfiles

- name: Clone dotfiles
  git:
    repo: 'https://github.com/thoughtbot/dotfiles/'
    dest: ~/dotfiles
    update: yes
  notify:
    - run rcup
  tags: dotfiles

- name: Clone dotfiles-local
  git:
    repo: 'git@codeberg.org:flowfx/dotfiles.git'
    dest: ~/dotfiles-local
    update: no
  notify:
    - run rcup
  tags: dotfiles
