---
- name: Ensure RCM is installed on Debian
  apt:
    name: rcm
  become: yes
  when: ansible_os_family == 'Debian'
  tags: dotfiles

- name: Ensure RCM is installed on Arch
  aur:
    name: rcm
    skip_installed: yes
  when: ansible_os_family == 'Archlinux'
  tags: dotfiles

- name: Ensure RCM is installed on macOS
  homebrew_tap:
    name: thoughtbot/formulae
  when: ansible_os_family == 'Darwin'
  tags: dotfiles

- name: Clone dotfiles
  git:
    repo: 'https://github.com/thoughtbot/dotfiles/'
    dest: ~/dotfiles
    update: yes
  notify:
    - run rcup
  tags: dotfiles

- name: Clone dotfiles-local
  git:
    repo: 'git@github.com:FlowFX/dotfiles.git'
    dest: ~/dotfiles-local
    update: no
  notify:
    - run rcup
  tags: dotfiles

