---
- name: Install fonts on Ubuntu/Debian
  apt:
    name: ['fonts-inconsolata']
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Debian'
  tags: fonts

- name: Tap cask-fonts
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
  when: ansible_facts['os_family'] == 'Darwin'
  tags: fonts

- name: Install fonts on macOS
  community.general.homebrew:
    name: font-inconsolata
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags: fonts
