---
- name: Install fonts on Arch
  pacman:
    name: ['ttf-inconsolata']
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'
  tags: fonts

- name: Install fonts from AUR
  aur:
    name: [
      'ttf-google-fonts-git',
      'noto-fonts',
      'noto-fonts-extra',
      'noto-fonts-emoji',
      'jetbrains-mono'
      ]
    skip_installed: no
  when: ansible_facts['os_family'] == 'Archlinux'
  tags: fonts
