---
# Configuration and Usage of the OneDrive Free Client
# https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md

- name: Add OneDrive PPA
  apt_repository:
    repo: ppa:yann1ck/onedrive
    state: present
  become: yes
  tags: onedrive
  register: aptstatus

- name: apt update if necessary
  apt:
    update_cache: yes
  when: aptstatus.changed == True
  become: yes
  tags: onedrive

- name: Install OneDrive sync
  apt:
    name: onedrive
    state: present
  become: yes
  tags: onedrive

- name: Disable and stop OneDrive as a system service
  systemd:
    name: onedrive@flowfx.service
    scope: system
    enabled: no
    state: stopped
  become: yes
  tags: onedrive

- name: Enable and start OneDrive as a user service
  systemd:
    name: onedrive.service
    scope: user
    enabled: yes
    state: started
  tags: onedrive
