- name: Install common packages on Linux
  package:
    name: '{{ packages }}'
  become: yes
  when: ansible_facts['os_family'] != 'Darwin'
  tags: packages

- name: Install common packages on macOS
  homebrew:
    name: '{{ packages }}'
  when: ansible_facts['os_family'] == 'Darwin'
  tags: packages

- name: Install specific packages on Debian
  apt:
    name: '{{ packages_debian }}'
  become: yes
  when: ansible_facts['os_family'] == 'Debian'
  tags: packages

- name: Install specific packages on macOS
  homebrew:
    name: '{{ packages_macos }}'
  when: ansible_facts['os_family'] == 'Darwin'
  tags: packages
