# https://thinkwiki.de/TLP_-_Linux_Stromsparen

- name: Add TLP PPA on Ubuntu Laptop
  apt_repository:
    repo: ppa:linrunner/tlp
    state: present
  become: yes
  when: ansible_hostname == 'hotmilk'
  tags: powersafe

- package:
    name: ['tlp', 'tlp-rdw', 'acpi-call-dkms']
    state: present
  become: yes
  when: ansible_hostname == 'hotmilk'
  tags: powersafe

- name: Enable TLP service
  systemd:
    name: tlp.service
    scope: system
    enabled: yes
    state: started
  become: yes
  when: ansible_hostname == 'hotmilk'
  tags: powersafe
