---
- name: Install Syncthing on Linux
  package:
    name: ['syncthing']
    state: present
  become: yes
  when: ansible_facts['os_family'] != 'Darwin'
  tags: syncthing

- name: Install Syncthing on macOS
  community.general.homebrew:
    name: ['syncthing', 'qsyncthingtray']
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags: syncthing
