---
- name: Install Syncthing on macOS
  community.general.homebrew:
    name: ['syncthing']
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  tags: syncthing

- name: Install Syncthing on Linux
  package:
    name: ['syncthing']
    state: present
  become: yes
  when: ansible_facts['os_family'] != 'Darwin'
  tags: syncthing

- name: Enable and start root Syncthing resume service
  systemd:
    name: syncthing-resume.service
    scope: system
    enabled: yes
    state: started
  become: yes
  when: ansible_facts['os_family'] != 'Darwin'
  tags: syncthing

- name: Enable Syncthing user service
  systemd:
    name: syncthing.service
    scope: user
    enabled: yes
    state: started
  when: ansible_facts['os_family'] != 'Darwin'
  tags: syncthing
