---
- name: Install Xorg, i3 & utilites
  package:
    name: ['xorg', 'i3', 'xcape', 'arandr', 'autorandr', 'maim', 'xclip']
    state: present
  become: yes
  tags: x11

- file:
    path: /etc/X11/xorg.conf.d
    state: directory
  become: yes
  tags: x11

- name: Configure keyboard layout
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBLAYOUT='
    line: XKBLAYOUT="eu"
    create: yes
  become: yes
  tags: x11

- name: Configure Caps key
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBOPTIONS='
    line: XKBOPTIONS="caps:ctrl_modifier"
    create: yes
  become: yes
  tags: x11
