- name: Clone dotfiles
  git:
    repo: 'https://github.com/thoughtbot/dotfiles/'
    dest: ~/dotfiles
    update: yes
  notify:
    - run rcup

- name: Clone dotfiles-local
  git:
    repo: 'git@github.com:FlowFX/dotfiles.git'
    dest: ~/dotfiles-local
    update: no
  notify:
    - run rcup

- name: Install RCM on ArchLinux
  aur:
    name: rcm
    skip_installed: yes
  when: ansible_os_family == 'Archlinux'

- name: Install RCM on OSX
  homebrew_tap:
    name: thoughtbot/formulae
  when: ansible_os_family == 'Darwin'
