- package:
    name: ['borg', 'pass']
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Enable borgbackup timer
  systemd:
    name: borgbackup.timer
    scope: user
    enabled: yes
  when: ansible_facts['os_family'] == 'Archlinux'

