#!/bin/sh
#
# https://wiki.archlinux.org/index.php/Acpid#Enabling_backlight_control

bl_dev=/sys/class/backlight/intel_backlight
step=2048

case $1 in
  -) echo $(($(< $bl_dev/brightness) - $step)) >$bl_dev/brightness;;
  +) echo $(($(< $bl_dev/brightness) + $step)) >$bl_dev/brightness;;
esac
