- name: Install Xorg, i3, and utilities
  package:
    name: [
      'xorg-server',
      'xorg-apps',
      'i3-wm',
      'arandr',
      'xcape',
      'autorandr'
      ]
    state: present
  become: yes

- name: Install fonts from AUR
  aur:
    name: ttf-google-fonts-git
    skip_installed: yes

- name: Enable autorandr service
  systemd:
    name: autorandr.service
    scope: system
    enabled: yes
    state: started
  become: yes
