- name: Ignore power key
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^HandlePowerKey='
    line: HandlePowerKey=ignore
  become: yes

- name: SuspendKey activates suspend-then-hibernate
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^HandleSuspendKey='
    line: HandleSuspendKey=suspend-then-hibernate
  become: yes

- name: LidSwitch activates suspend-then-hibernate
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^HandleLidSwitch='
    line: HandleLidSwitch=suspend-then-hibernate
  become: yes

- lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^HandleLidSwitchExternalPower='
    line: HandleLidSwitchExternalPower=suspend-then-hibernate
  become: yes

- lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^HandleLidSwitchDocked='
    line: HandleLidSwitchDocked=suspend-then-hibernate
  become: yes
