---
- include: logind_conf.yml
  when: ansible_facts['os_family'] != 'Darwin'

- include: sleep_conf.yml
  when: ansible_facts['os_family'] != 'Darwin'

- include: tlp.yml
  when: ansible_facts['os_family'] != 'Darwin'

