# https://wiki.archlinux.org/index.php/TLP

- pacman:
    name: tlp
    state: present
  become: yes

- name: Enable TLP service
  systemd:
    name: tlp.service
    scope: system
    enabled: yes
    state: started
  become: yes

- name: Ensure SuspendThenHibernate is enabled
  lineinfile:
    path: /etc/systemd/sleep.conf
    regexp: '^AllowSuspendThenHibernate='
    line: AllowSuspendThenHibernate=yes
  become: yes

- name: Ensure SuspendThenHibernate is delayed for 3h
  lineinfile:
    path: /etc/systemd/sleep.conf
    regexp: '^HibernateDelaySec='
    line: HibernateDelaySec=10800
  become: yes
