---
- include: logind_conf.yml
  when: ansible_facts['os_family'] == 'Archlinux'

- include: sleep_conf.yml
  when: ansible_facts['os_family'] == 'Archlinux'

- include: tlp.yml
  when: ansible_facts['os_family'] == 'Archlinux'

