# https://wiki.archlinux.org/index.php/TLP

- pacman:
    name: tlp
    state: present
  become: yes

- name: Enable TLP service
  systemd:
    name: tlp.service
    scope: system
    enabled: yes
    state: started
  become: yes
