# Linux
- package:
    name: ['khard', 'vdirsyncer']
    state: present
  become: yes
  when: (ansible_facts['os_family'] == 'Archlinux') or
        (ansible_facts['os_family'] == 'Debian')

# macOS
- homebrew:
    name: ['khard', 'vdirsyncer']
  when: ansible_facts['os_family'] == 'Darwin'
