# Linux
# https://wiki.archlinux.org/index.php/OfflineIMAP
- package:
    name: offlineimap
    state: present
  become: yes
  when: (ansible_facts['os_family'] == 'Archlinux') or
        (ansible_facts['os_family'] == 'Debian')

- name: Disable offlineimap-oneshot timer
  systemd:
    name: offlineimap-oneshot.timer
    scope: user
    enabled: no
    state: stopped
  when: (ansible_facts['os_family'] == 'Archlinux') or
        (ansible_facts['os_family'] == 'Debian')

# macOS
- homebrew:
    name: offlineimap
  when: ansible_facts['os_family'] == 'Darwin'
