- name: Install Xorg, i3, and utilities
  package:
    name: [
      'xorg-server',
      'xorg-apps',
      'i3-wm',
      'xcape',
      'arandr',
      'autorandr',
      'maim',
      'xclip'
      ]
    state: present
  become: yes

- name: Install fonts from AUR
  aur:
    name: ttf-google-fonts-git
    skip_installed: yes

- name: Copy X11 keyboard settings
  copy:
    src: 00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'
