- homebrew:
    name: '{{ packages }}'
  when: ansible_facts['os_family'] == 'Darwin'

- pacman:
    name: '{{ packages }}'
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- pacman:
    name: '{{ packages_arch }}'
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Enable NTP Service
  systemd:
    name: ntpd.service
    scope: system
    enabled: yes
    state: started
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

# Cleaning the package cache
# https://wiki.archlinux.org/index.php/pacman#Cleaning_the_package_cache
- pacman:
    name: pacman-contrib
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Enable paccache.timer
  systemd:
    name: paccache.timer
    scope: system
    enabled: yes
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'
