- name: Install ACPID
  pacman:
    name: acpid
    state: present
  become: yes

- name: Enable ACPID
  systemd:
    name: acpid.service
    scope: system
    enabled: yes
    state: started
  become: yes

- name: Copy handler.sh into place
  copy:
    src: handler.sh
    dest: /etc/acpi
    owner: root
    group: root
    mode: preserve
  become: yes
  notify:
    - restart acpid

- name: Copy events directory into place
  copy:
    src: events
    dest: /etc/acpi
    owner: root
    group: root
    mode: preserve
  become: yes
  notify:
    - restart acpid

- name: Copy handers directory into place
  copy:
    src: handlers
    dest: /etc/acpi
    owner: root
    group: root
    mode: preserve
  become: yes
  notify:
    - restart acpid
