- pacman:
    name: '{{ packages }}'
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- homebrew:
    name: '{{ packages }}'
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
